const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.TextBox,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{fondoinicio: 0},
	{logo: 0},
	{barrablanca: 0},
	{sinjov: 0},
	{porun: 0},
	{derechos: 0},
	{Inicio: 0},
	{quebusca: 0},
	{deten: 0},
	{manual: 0},
	{contact: 0},
	{fondo2: 0},
	{barraabajo: 0},
	{sinjov2: 0},
	{btn: 0},
	{sinjov3: 0},
	{sinjov4: 0},
	{sinjov5: 0},
	{sinjov6: 0},
	{sinjov7: 0},
	{sinjov8: 0},
	{Recurso: 0},
	{Recurso2: 0},
	{Recurso3: 0},
	{Recurso4: 0},
	{Recurso5: 0},
	{Recurso6: 0},
	{sinjov9: 0},
	{sinjov10: 0},
	{sinjov11: 0},
	{sinjov12: 0},
	{sinjov13: 0},
	{sinjov14: 0},
	{sinjov15: 0},
	{sinjov16: 0},
	{sinjov17: 0},
	{sinjov18: 0},
	{Sprite: 0},
	{sinjov19: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{sinjov20: 0},
	{sinjov21: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{sinjov22: 0},
	{Touch: 0},
	{Mouse: 0},
	{Keyboard: 0},
	{sinjov23: 0},
	{sinjov24: 0},
	{sinjov25: 0},
	{sinjov26: 0},
	{sinjov27: 0},
	{sinjov28: 0},
	{sinjov29: 0},
	{sinjov30: 0},
	{sinjov31: 0},
	{sinjov32: 0},
	{sinjov33: 0},
	{TextInput: 0},
	{TextInput2: 0},
	{TextInput3: 0},
	{TextInput4: 0},
	{sinjov34: 0},
	{derechos2: 0},
	{sinjov35: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0}
];

self.InstanceType = {
	fondoinicio: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	barrablanca: class extends self.ISpriteInstance {},
	sinjov: class extends self.ITextInstance {},
	porun: class extends self.ITextInstance {},
	derechos: class extends self.ITextInstance {},
	Inicio: class extends self.ITextInstance {},
	quebusca: class extends self.ITextInstance {},
	deten: class extends self.ITextInstance {},
	manual: class extends self.ITextInstance {},
	contact: class extends self.ITextInstance {},
	fondo2: class extends self.ISpriteInstance {},
	barraabajo: class extends self.ISpriteInstance {},
	sinjov2: class extends self.ITextInstance {},
	btn: class extends self.ISpriteInstance {},
	sinjov3: class extends self.ITextInstance {},
	sinjov4: class extends self.ITextInstance {},
	sinjov5: class extends self.ITextInstance {},
	sinjov6: class extends self.ITextInstance {},
	sinjov7: class extends self.ITextInstance {},
	sinjov8: class extends self.ITextInstance {},
	Recurso: class extends self.ISpriteInstance {},
	Recurso2: class extends self.ISpriteInstance {},
	Recurso3: class extends self.ISpriteInstance {},
	Recurso4: class extends self.ISpriteInstance {},
	Recurso5: class extends self.ISpriteInstance {},
	Recurso6: class extends self.ISpriteInstance {},
	sinjov9: class extends self.ITextInstance {},
	sinjov10: class extends self.ITextInstance {},
	sinjov11: class extends self.ITextInstance {},
	sinjov12: class extends self.ITextInstance {},
	sinjov13: class extends self.ITextInstance {},
	sinjov14: class extends self.ITextInstance {},
	sinjov15: class extends self.ITextInstance {},
	sinjov16: class extends self.ITextInstance {},
	sinjov17: class extends self.ITextInstance {},
	sinjov18: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	sinjov19: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	sinjov20: class extends self.ITextInstance {},
	sinjov21: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	sinjov22: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	sinjov23: class extends self.ITextInstance {},
	sinjov24: class extends self.ITextInstance {},
	sinjov25: class extends self.ITextInstance {},
	sinjov26: class extends self.ITextInstance {},
	sinjov27: class extends self.ITextInstance {},
	sinjov28: class extends self.ITextInstance {},
	sinjov29: class extends self.ITextInstance {},
	sinjov30: class extends self.ITextInstance {},
	sinjov31: class extends self.ITextInstance {},
	sinjov32: class extends self.ITextInstance {},
	sinjov33: class extends self.ITextInstance {},
	TextInput: class extends self.ITextInputInstance {},
	TextInput2: class extends self.ITextInputInstance {},
	TextInput3: class extends self.ITextInputInstance {},
	TextInput4: class extends self.ITextInputInstance {},
	sinjov34: class extends self.ITextInstance {},
	derechos2: class extends self.ITextInstance {},
	sinjov35: class extends self.ITextInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {}
}